### ISSUE TITLE
How TaskIdRepr was defined?

### ISSUE THREAD

**Issue by Gonta01** [fprime-community/fprime-zephyr-led-blinker#3]
@ethancheez hi!
Could you please give a hint how have you resolved [this ](https://github.com/nasa/fprime/discussions/2834)problem in [fprime-zephyr-led-blinker](https://github.com/fprime-community/fprime-zephyr-led-blinker) project?

I haven't found definition of TGT_OS_TYPE_VXWORKS nor FW_BAREMETAL_SCHEDULER here , so I guess that some proper solution is used.

**Comment by ethancheez** [comment]
> @ethancheez hi!
> 
> Could you please give a hint how have you resolved [this ](https://github.com/nasa/fprime/discussions/2834)problem in [fprime-zephyr-led-blinker](https://github.com/fprime-community/fprime-zephyr-led-blinker) project?
> 
> 
> 
> I haven't found definition of TGT_OS_TYPE_VXWORKS nor FW_BAREMETAL_SCHEDULER here , so I guess that some proper solution is used.

I replaced the default FPrime OS Task implementation with a Zephyr OS layer in fprime-zephyr. 

To solve the TaskIdRepr type, I created it [here](https://github.com/ethancheez/fprime-zephyr/blob/4898f5694e20abeba2d04089bee3c8e0e24f67e5/cmake/platform/types/PlatformTypes.h#L39). Zephyr has its own implementation of the thread ID (like how Linux is pthread_t). It is k_tid_t. I didn't want to edit the FPrime files directly like you said, so PlatformTypes.h made the most sense.

**Comment by Gonta01** [comment]
@ethancheez thank you a lot.
